-- 환자 정보
CREATE TABLE MEDICAL_MEMBER(
	MEM_NUM VARCHAR(20) PRIMARY KEY
	,MEM_NAME VARCHAR(20) NOT NULL
	,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
	,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
	,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);
SELECT * FROM medical_member; 
SELECT * FROM medical_doctor;
SELECT * FROM MEDICAL_DEPT;
SELECT * FROM medical_doctor;
SELECT * FROM DOCTOR_IMG;
DELETE FROM medical_member
WHERE MEM_NAME = '1111';
SELECT CONCAT(
    IF('ADMIN' = 'USER', 'CTL_', 'DOC_'),
    LPAD(IFNULL(MAX(CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)), 0) + 1, 5, '0')
) AS mem_num -- 
FROM medical_member
WHERE MEM_ROLE = 'ADMIN';
-- 의사랑 클라랑 두개 들어가는 테이블
-- 관리자 키 만드는거( DOC_ , ROLE 어드민 들어가기 위한 키값을 넣어야 이게 바뀐다)

-- 진료과
DROP TABLE MEDICAL_MEMBER;
DROP TABLE medical_dept;
DROP TABLE medical_doctor;
DROP TABLE medical_schedule;
DROP TABLE DOCTOR_IMG;
DELETE FROM medical_member;
CREATE TABLE MEDICAL_DEPT(
	DEPT_NUM INT PRIMARY KEY AUTO_INCREMENT 
	,DEPT_NAME VARCHAR(30) NOT NULL
	
);
-- 의료진
CREATE TABLE MEDICAL_DOCTOR(
	DOC_NUM VARCHAR(20) PRIMARY KEY 
	,DOC_NAME VARCHAR(20) NOT NULL
	,DEPT_NUM INT  REFERENCES MEDICAL_DEPT(DEPT_NUM) ON DELETE CASCADE
	,FOREIGN KEY (DOC_NUM) REFERENCES MEDICAL_MEMBER(MEM_NUM)
	
);
-- 이미지
CREATE TABLE DOCTOR_IMG(
IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
, ORIGIN_FILE_NAME VARCHAR(50)
, ATTACHED_FILE_NAME VARCHAR(50) 
, DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM)
);
-- 예약
CREATE TABLE MEDICAL_schedulE(
	SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NUM VARCHAR(20) REFERENCES MEDICAL_DOCTOR(DOC_NUM) ON DELETE CASCADE
	,MEM_NUM VARCHAR(20) REFERENCES MEDICAL_MEMBER(MEM_NUM) ON DELETE CASCADE
	,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
	,SCH_DATE DATETIME -- 예약날짜 건들일 예정
	,DETAIL VARCHAR(100)
	,SCH_STATUS VARCHAR(10) DEFAULT('Y')
);
SELECT CONCAT(
            IF('USER' = 'ADMIN', 'CTL_', 'DOC_'),
            LPAD(IFNULL(MAX(CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)), 0) + 1, 5, '0') 
            ) AS mem_num
    FROM medical_member
    WHERE MEM_ROLE = 'ADMIN';


SELECT CASE
       WHEN MEM_ROLE = 'ADMIN' THEN 'DOC_'
       WHEN MEM_ROLE = 'USER' THEN 'CLT_'
   END
FROM medical_member
WHERE MEM_ROLE = 'USER';  


SUBSTRING(MEM_NUM, 5)
SELECT CONCAT(
            CASE
                WHEN MEM_ROLE = 'ADMIN' THEN 'DOC_'
                WHEN MEM_ROLE = 'USER' THEN 'CLT_'
            END,
            LPAD(IFNULL(MAX(CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)), 0) + 1, 5, '0') MEM_NUM
    FROM medical_member;
SELECT  FROM medical_doctor;

SELECT * FROM medical_doctor;
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(1,'유방암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(2,'뇌종양');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(3,'갑상선암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(4,'간암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(5,'폐암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(6,'혈액암');
SELECT * FROM medical_member
;




CREATE TABLE medical_member2(
	MEM_NUM VARCHAR(50) PRIMARY KEY
	,MEM_NAME VARCHAR(20) NOT NULL
	,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
	,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
	,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);

INSERT INTO medical_member2 (
	MEM_NUM
 	,MEM_NAME
	,MEM_TEL
	,MEM_RRN
)VALUES (
	'DOC_00001'
	, '김수한무'
	,'11011112226'
	,'5604232222227'
);

SELECT * FROM medical_member2;

UPDATE medical_member2
SET MEM_ROLE = 'ADMIN'
WHERE MEM_NUM LIKE 'DOC%';

DELETE FROM medical_member2;

-- 다음에 들어갈 의사번호 조회
SELECT MEM_NUM
	, SUBSTRING(MEM_NUM, 5)
	, CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)
FROM medical_member2;

-- DOC_00002
SELECT CONCAT(IF('DOC_'),LPAD(IFNULL(MAX(CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)), 0) + 1, 5, '0'))    
FROM medical_member2
WHERE MEM_ROLE = 'ADMIN'; 


SELECT CONCAT('DOC_',LPAD(IFNULL(MAX(CAST(SUBSTRING(MEM_NUM, 5) AS UNSIGNED)), 0) + 1, 5, '0'))    
FROM medical_member2;


IFNULL(?, 0)


SELECT LPAD(3, 5, '0'), CONCAT('AA', 'BB') FROM medical_member2;

SELECT *
        FROM SALES_INFO,CAR_INFO
        WHERE CAR_INFO.MODEL_NUM = SALES_INFO.MODEL_NUM;
-- 의료진, 의사 JOIN select
SELECT DOC_NAME, DEPT_NAME
FROM medical_dept, medical_doctor
WHERE medical_dept.DEPT_NUM = medical_doctor.DEPT_NUM;

INSERT INTO medical_doctor(DOC_NAME, DEPT_NUM) VALUES ('김현경', 1);
INSERT INTO medical_doctor(DOC_NUM,DOC_NAME, DEPT_NUM) VALUES (8,'민정흠', 2);
INSERT INTO medical_doctor(DOC_NUM,DOC_NAME, DEPT_NUM) VALUES (9,'유지현', 3);
INSERT INTO medical_doctor(DOC_NUM,DOC_NAME, DEPT_NUM) VALUES (10,'서은송', 4);
INSERT INTO medical_doctor(DOC_NUM,DOC_NAME, DEPT_NUM) VALUES (11,'김형진', 5);
INSERT INTO medical_doctor(DOC_NUM,DOC_NAME, DEPT_NUM) VALUES (12,'정다영', 6);