-- 1. 테이블 생성
CREATE TABLE MY_MEMBER (
	MEM_NUM INT PRIMARY KEY
	,MEM_ID VARCHAR(50) NOT NULL
	,MEM_PW VARCHAR(50) NOT NULL
	,MEM_NAME VARCHAR(50) NOT NULL
	,MEM_AGE INT
	,MEM_EMAIL VARCHAR(50)
);
-- 2. 데이터 삽입/삭제
INSERT INTO MY_MEMBER 
VALUES (1,'1','2','3',42,'2');
DELETE FROM MY_MEMBER;

-- 3. 데이터 수정
UPDATE MY_MEMBER SET 
MEM_NAME = '김자바',MEM_ID = 'KIMJAVA'
WHERE MEM_NUM = 1;

-- 4.
