-- 테이블 삭제(데이터 삭제와 구분)
DROP TABLE BASIC_BOARD; -- 테이블 삭제
DELETE FROM BASIC_BOARD; -- 데이터 삭제

-- 게시판 프로그램 테이블 생성
CREATE TABLE BASIC_BOARD (
	-- 컬럼명 데이터타입 [제약조건들]
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, TITLE VARCHAR(50) NOT NULL 
	, WRITER VARCHAR(50) NOT NULL 
	, CONTENT VARCHAR(100) 
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, READ_CNT INT DEFAULT 0 
);

INSERT INTO BASIC_BOARD(TITLE, WRITER, CONTENT) 
VALUES('1', '1', '1');

INSERT INTO BASIC_BOARD(TITLE, WRITER) 
VALUES( , '제목','작성자1');

INSERT INTO BASIC_BOARD(BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT) 
VALUES(1, 'EE', 'E작성자', 'E내용', '2024-07-01', 5);

INSERT INTO BASIC_BOARD(BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE) 
VALUES(6, '', '2작성자', '2내용', '2024-07-01');

INSERT INTO BASIC_BOARD(BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT) 
VALUES(2, '제목', '작성자', '내용', '2024-07-01', 3);



SELECT * FROM basic_board;

SELECT BOARD_NUM
	, TITLE
	, WRITER
	, CREATE_DATE
	, READ_CNT
FROM basic_board
WHERE TITLE LIKE '%안녕%';
WHERE WRITER LIKE '%java%'  '%';