CREATE TABLE AAAA(
	NUMBERS VARCHAR(50) PRIMARY KEY
	, TITLE VARCHAR(20)
	
);
SELECT * FROM AAAA;

INSERT INTO AAAA (numbers,title) 
SELECT 
	CONCAT('DOC_',lpad(IFNULL(max(CAST(SUBSTRING(NUMBERS,5) AS UNSIGNED)),0)+1,4,'0')) ,
	'AA'
FROM aaaa; 
SELECT max(SUBSTRING(NUMBERS,5)) FROM AAAA;
-- 다음 들어갈 데이터
DELETE FROM aaaa;
CONCAT('DOC_',lpad(max(CAST(SUBSTRING(NUMBERS,5) AS UNSIGNED))+1,4,0))



